import Head from 'next/head';
import Footer from './Footer';
import Navbar from './Navbar';

export default function Home({ title, children }) {
  return (
    <>
      <Head>
        <title>IG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-between min-h-screen">
        <header>
          <Navbar />
        </header>

        <main className="">{children}</main>

        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
}
